
# This file is automatically generated by setup.py, So don't edit it. :)
version_info = {
    'final': False,
    'version': '',
    'branch_nick': 'master',
    'revision_id': '8c425ae751151c3f6201d250c80cb3e6872dc4d9',
    'revno': 17
}
