
# This file is automatically generated by setup.py, So don't edit it. :)
version_info = {
    'final': False,
    'version': '',
    'branch_nick': 'master',
    'revision_id': '070fc7ec736ec95d56f445a46993bf56798fd72f',
    'revno': 16
}
