
# This file is automatically generated by setup.py, So don't edit it. :)
version_info = {
    'final': False,
    'version': '0.2.10-6-ge4b8003',
    'branch_nick': 'master',
    'revision_id': 'e4b8003a2a5c1a3bd3b912be2cf24832707f0b08',
    'revno': 1670
}
